In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
env

<TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>

In [5]:
env.observation_space.n

16

In [6]:
env.action_space.n

4

In [7]:
# initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

In [8]:
# set learning parameters
lr = 0.8
y = 0.95
num_episodes = 2000

In [15]:
rList = []
for i in range(num_episodes):
    # reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    # tabular Q-learning
    while j < 99:
        j += 1
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1.0 / (i + 1)))
        s1, r, d, _ = env.step(a)
        Q[s, a] = Q[s, a] + lr * (r + y * np.max(Q[s1, :]) - Q[s, a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [16]:
print('Score over time: ' + str(sum(rList) / num_episodes))
print(Q)

Score over time: 0.563
[[3.61599857e-01 9.84968791e-03 7.96000065e-03 1.06847045e-02]
 [1.91302225e-03 2.93333308e-03 4.30911717e-03 3.05594074e-01]
 [2.04034072e-03 1.52449025e-03 2.14150646e-03 2.01368476e-01]
 [1.68368207e-03 5.87587713e-04 3.04685361e-04 5.72634677e-02]
 [5.70040490e-01 3.73152841e-03 7.54682646e-04 1.15804104e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.13136952e-04 3.90049362e-05 1.31829420e-01 2.36836885e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.88375688e-05 1.39420841e-03 1.15256379e-03 4.03729575e-01]
 [3.33625631e-03 7.10116498e-01 0.00000000e+00 7.15202619e-03]
 [2.38582262e-01 1.05940453e-03 6.79732946e-04 7.70738066e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.61845379e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.53326625e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 