# ConvTranspose1D Test
- https://medium.com/@santi.pdp/how-pytorch-transposed-convs1d-work-a7adac63c4a5

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Conv1d

In [4]:
# (batch_size, channel, length)
x = torch.ones(1, 1, 7)

In [6]:
conv = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, bias=False)
conv

Conv1d(1, 1, kernel_size=(3,), stride=(1,), bias=False)

In [12]:
# (out_channel, in_channel, kernel_size)
conv.weight.data = torch.ones(1, 1, 3)
conv.weight

Parameter containing:
tensor([[[1., 1., 1.]]], requires_grad=True)

In [13]:
y = conv(x)

In [14]:
y

tensor([[[3., 3., 3., 3., 3.]]], grad_fn=<SqueezeBackward1>)

In [23]:
conv = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=1, bias=False)
conv

Conv1d(1, 1, kernel_size=(3,), stride=(1,), padding=(1,), bias=False)

In [24]:
conv.weight.data = torch.ones(1, 1, 3)
conv.weight

Parameter containing:
tensor([[[1., 1., 1.]]], requires_grad=True)

In [25]:
y = conv(x)

In [26]:
y

tensor([[[2., 3., 3., 3., 3., 3., 2.]]], grad_fn=<SqueezeBackward1>)

## ConvTranspose1d

In [49]:
# (batch_size, channel, length) 
y = torch.ones(1, 1, 1)

In [50]:
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, bias=False)

In [51]:
deconv

ConvTranspose1d(1, 1, kernel_size=(3,), stride=(1,), bias=False)

In [52]:
deconv.weight.data

tensor([[[ 0.0571,  0.4288, -0.2723]]])

In [53]:
x = deconv(y)

In [54]:
x

tensor([[[ 0.0571,  0.4288, -0.2723]]], grad_fn=<SqueezeBackward1>)

## 入力の長さが長い場合

In [78]:
y = torch.ones(1, 1, 2)
y

tensor([[[1., 1.]]])

In [79]:
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, bias=False)
deconv.weight.data = torch.ones(1, 1, 3)
x = deconv(y)

In [80]:
x

tensor([[[1., 2., 2., 1.]]], grad_fn=<SqueezeBackward1>)

In [89]:
# stride=2
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, bias=False)
deconv.weight.data = torch.ones(1, 1, 3)
print(deconv)
x = deconv(y)
x

ConvTranspose1d(1, 1, kernel_size=(3,), stride=(2,), bias=False)


tensor([[[1., 1., 2., 1., 1.]]], grad_fn=<SqueezeBackward1>)

In [87]:
# stride=3
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=3, padding=0, bias=False)
deconv.weight.data = torch.ones(1, 1, 3)
x = deconv(y)
x

tensor([[[1., 1., 1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)

In [88]:
# stride=4
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=3, stride=4, padding=0, bias=False)
deconv.weight.data = torch.ones(1, 1, 3)
x = deconv(y)
x

tensor([[[1., 1., 1., 0., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)

In [95]:
# stride=4, kernel_size=4
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=4, stride=4, padding=0, bias=False)
deconv.weight.data = torch.ones(1, 1, 4)
x = deconv(y)
x

tensor([[[1., 1., 1., 1., 1., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)

In [96]:
# stride=4, kernel_size=8
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=8, stride=4, padding=0, bias=False)
deconv.weight.data = torch.ones(1, 1, 8)
x = deconv(y)
x

tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 1., 1., 1., 1.]]],
       grad_fn=<SqueezeBackward1>)

In [99]:
# stride=4, kernel_size=8, padding=2
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=8, stride=4, padding=2, bias=False)
deconv.weight.data = torch.ones(1, 1, 8)
x = deconv(y)
x

tensor([[[1., 1., 2., 2., 2., 2., 1., 1.]]], grad_fn=<SqueezeBackward1>)

In [102]:
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=8, stride=4, padding=0, output_padding=1, bias=False)
deconv.weight.data = torch.ones(1, 1, 8)
x = deconv(y)
x

tensor([[[1., 1., 1., 1., 2., 2., 2., 2., 1., 1., 1., 1., 0.]]],
       grad_fn=<SqueezeBackward1>)

In [103]:
y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=8, stride=4, padding=2, output_padding=1, bias=False)
deconv.weight.data = torch.ones(1, 1, 8)
x = deconv(y)
x

tensor([[[1., 1., 2., 2., 2., 2., 1., 1., 1.]]], grad_fn=<SqueezeBackward1>)